<h2 class="futura">Bienvenue sur notre site <a href="http://www.facebook.com/#!/group.php?gid=70994050067" target="_BLANK"> <img border="0" src="images/facebook.png" width="25"></a></h2>
<p><span class=Soustitre>Québec Natation est une école de natation qui possède une expérience de plus de 40 ans dans le domaine de l'enseignement de la natation à Québec et les environs. Ses 160 employés en font la plus grosse école de natation dans la région de Québec et la deuxième au Québec, après la ville de Montréal.</span></p>

<p><span class=Texte>Nous offrons une programmation pour toutes les clientèles à partir de l'âge de six mois avec les programmes Préscolaire, Junior, Aquadultes, Assistant-Moniteur et Moniteur en sécurité aquatique de la Croix-Rouge. Pour les adolescents qui rechercheront éventuellement un emploi comme moniteur ou sauveteur, les cours des niveaux bronze et le cours de moniteur en sauvetage, de même que les cours de sauveteur national options piscine et plage continentale de la Société de Sauvetage font aussi parti de notre programme régulier.</p>
<p><span class=Texte>Les cours qui sont offert à Québec Natation inc. couvrent toute la programmation aquatique de la Croix-Rouge, les principaux programmes de la Société de Sauvetage et des programmes de maîtres nageurs, aquaforme, aquajogging et pré-post natal.</span></p>
<p><span class=Texte>Appelez nous sans tarder: (418) 687-4045</span></p>

<h6 class="futura">Moniteur et assistants moniteur : Envoyez votre candidature en ligne <a href="index.php?Section=CV">en cliquant ici</a></h6>
<h6 class="futura">Procédure de remboursement:  <a href="procedure.pdf">cliquez ici</a></h6>
