<p><h4 class=futura>AquAdulte - Styles de nage</h4></p>

<p><span class="SousTitre">Objectifs</span>
<span class="Texte"><br>
&nbsp;&nbsp;&nbsp;&#8226;	Maintenir ou am&eacute;liorer le style de nage et l&#8217;endurance. <br>

&nbsp;&nbsp;&nbsp;&#8226;	Introduire d&#8217;autres formes d&#8217;activit&eacute;s aquatiques pour le plaisir et le conditionnement physique. <br>
&nbsp;&nbsp;&nbsp;&#8226;	Introduire ou approfondir des connaissances et habilet&eacute;s en mati&egrave;re de s&eacute;curit&eacute; aquatique pertinentes pour l&#8217;&eacute;l&egrave;ve.</span></p>

<span class="SousTitre">Aper&ccedil;u du programme</span>
<span class="Texte"><br>
&nbsp;&nbsp;&nbsp;&#8226;	D&eacute;veloppement plus pouss&eacute; de la ma&icirc;trise de style de nage et de l&#8217;endurance. <br>

&nbsp;&nbsp;&nbsp;&#8226;	Proc&eacute;dures pour le &laquo; r&eacute;chauffement/r&eacute;cup&eacute;ration &raquo; et contr&ocirc;le du rythme cardiaque. <br>
&nbsp;&nbsp;&nbsp;&#8226;	S&eacute;curit&eacute; aquatique de base (si elle n&#8217;a pas d&eacute;j&agrave; &eacute;t&eacute; couverte).<br>

&nbsp;&nbsp;&nbsp;&#8226;	Modules de s&eacute;curit&eacute; aquatique, tels qu&#8217;indiqu&eacute;s sur la fiche d&#8217;apprentissage de l&#8217;&eacute;l&egrave;ve. <br>
&nbsp;&nbsp;&nbsp;&#8226;	Les moniteurs consultent leurs &eacute;l&egrave;ves pour d&eacute;terminer les buts et les priorit&eacute;s d&#8217;apprentissage.</span>
</p>

