<p><span class="SousTitre">Natation</span>
<span class="Texte"><br>
&nbsp;&nbsp;&nbsp;&#8226;	Crawl, 100 m <br>
&nbsp;&nbsp;&nbsp;&#8226;	Dos Crawl&eacute;, 100 m <br>
&nbsp;&nbsp;&nbsp;&#8226;	Dos &eacute;l&eacute;mentaire, 50 m<br>
&nbsp;&nbsp;&nbsp;&#8226;	Brasse, 50 m</span></p>



<span class="SousTitre">Activit&eacute;s de conditionnement physique</span>
<span class="Texte"><br>
&nbsp;&nbsp;		Exercices de battement des jambes : <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;		&#8226; battement du dauphin (vertical), 3 x 10 sec.<br>
&nbsp;&nbsp;		Style de nage: Papillon, 3 x 10 m<br>
&nbsp;&nbsp;		Nage d&#8217;endurance : <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;		&#8226; 500 m<br>
</span></p>


<p><span class="SousTitre">Techniques et s&eacute;curit&eacute; aquatique</span>
<span class="Texte"><br>

&nbsp;&nbsp;	&#8226;	La s&eacute;curit&eacute; au soleil<br>
&nbsp;&nbsp;	&#8226;		Sauvetage sur glace &agrave; partir d&#8217;une zone s&eacute;curitaire<br>
&nbsp;&nbsp;	&#8226;		Statistiques de noyade<br>

&nbsp;&nbsp;	&#8226;		Prochaines &eacute;tapes<br>
&nbsp;&nbsp;	&#8226;	Plongeon de surface t&ecirc;te et pieds en premier avec nage sous l&#8217;eau, 2 m<br>
</span></p>

