<p><span class="SousTitre">Natation</span>
<span class="Texte"><br>
 &nbsp;&nbsp;&nbsp;&#8226;	Crawl, 3 x 25 m (en une le&ccedil;on)<br>
&nbsp;&nbsp;&nbsp;&#8226;	Dos crawl&eacute;, 3 x 25 m (en une le&ccedil;on)<br>
&nbsp;&nbsp;&nbsp;&#8226;	Dos &eacute;l&eacute;mentaire <br>

&nbsp;&nbsp;&nbsp;&#8226;	3 x 15 m (en une le&ccedil;on)</span></p>

<p><span class="SousTitre">Activit&eacute;s de conditionnement physique</span>
<span class="Texte"><br>
&nbsp;&nbsp;	Exercices de battement des 
jambes : <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	3 x 25 m<br>
&nbsp;&nbsp;	Nage d&#8217;endurance : <br>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	75 m</span></p>

<p><span class="SousTitre">Techniques et s&eacute;curit&eacute; aquatique</span>
<span class="Texte"><br>
&nbsp;&nbsp;	&#8226;	Causes d&#8217;incidents nautiques<br>
&nbsp;&nbsp;	&#8226;	Quand et o&ugrave; aller sur la glace<br>

&nbsp;&nbsp;	&#8226;	Reconna&icirc;tre et simuler des nageurs en difficult&eacute;<br>
&nbsp;&nbsp;	&#8226;	Objets &agrave; lancer avec aide <br>
&nbsp;&nbsp;	&#8226;	Godille sur le dos t&ecirc;te premi&egrave;re, 5 m<br>

&nbsp;&nbsp;	&#8226;	Nager debout, 1:30, en eau profonde<br>
&nbsp;&nbsp;	&#8226;	Plongeon en avant</span></p>

