<p><span class="SousTitre">Natation</span><br>
<span class="Texte">
&nbsp;&nbsp;&nbsp;&#8226;	Respiration rythm&eacute;e, dix fois (des deux c&ocirc;t&eacute;s)<br>
&nbsp;&nbsp;&nbsp;&#8226;	Transfert de poids en eau peu profonde<br>
&nbsp;&nbsp;&nbsp;Glisser : <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	Glissement sur le ventre avec battement des jambes, 3x2 m<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	Glissement sur le dos avec battement des jambes,  2 m<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	Glissement sur le c&ocirc;t&eacute; avec battement des jambes, 1 m<br>
&nbsp;&nbsp;&nbsp;Nager : <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	Nage sur le ventre, 5 m<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	Nage sur le dos, 5 m<br>
</span>
</p>
<span class="SousTitre">Activit&eacute;s de conditionnement physique</span><br>

<span class="Texte">&nbsp;&nbsp;	Activit&eacute;s aquatiques :<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	introduction &agrave; la nage synchronis&eacute;e (baignoire et flottaison) <br>
&nbsp;&nbsp;	Exercices de battement des 	jambes :<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#8226;&nbsp;battement des jambes avec objet flottant, 10 m<br>
&nbsp;&nbsp;	Style de nage :<br>
&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&#8226;	Battement de dauphin (avec aide)<br>
&nbsp;&nbsp;	Nage d&#8217;endurance : <br>
&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&#8226;	10 m
</br>
</p>

<p><span class="SousTitre">Techniques et s&eacute;curit&eacute; aquatique</span><br>
<span class="Texte">
&nbsp;&nbsp;	&#8226;	S&eacute;ance d&#8217;orientation sur l&#8217;&eacute;tablissement et supervision active <br>
&nbsp;&nbsp;	&#8226;	Arr&ecirc;te! Regarde! Demande!<br>

&nbsp;&nbsp;	&#8226;	Saut en eau profonde<br>
&nbsp;&nbsp;	&#8226;	Le VFI et moi  en eau profonde<br>
&nbsp;&nbsp;	&#8226;	Changement de direction en eau profonde (avec aide)<br>
&nbsp;&nbsp;	&#8226;	Maintien &agrave; la surface, 10 sec.<br>

&nbsp;&nbsp;	&#8226;	Saut dans l&#8217;eau profonde, maintien &agrave; la surface, 5 sec <br>
&nbsp;&nbsp;	&#8226;	Arr&ecirc;te! Demande de l&#8217;aide!<br>
</span>
</p>

