<p><span class="SousTitre">Natation</span><br>
<span class="Texte">
 &nbsp;&nbsp;&nbsp;&#8226;	Ouvre les yeux sous l&#8217;eau (tentative)<br>
&nbsp;&nbsp;&nbsp;&#8226;	Respiration rythm&eacute;e, trois fois<br>
&nbsp;&nbsp;&nbsp;Flotter : <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	Flottaison sur le ventre avec redressement 3 sec.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	Flottaison sur le dos avec redressement 3 sec.<br>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	Flottaison avec retournement 3 sec. (avec aide) <br>
&nbsp;&nbsp;&nbsp;Glisser : <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	Glissement sur le ventre 3 sec. <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	Glissement sur le ventre avec battement des jambes, 5 sec. (avec aide) <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	Glissement sur le dos 3 sec (avec aide)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	Glissement sur le dos avec battement des jambes, 5 sec. (avec aide) <br>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	Glissement avec retournement et battement des jambes, 6 sec. <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(avec aide)<br>
&nbsp;&nbsp;&nbsp;Nager :<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	 nage sur le ventre, 2 m (avec aide)<br>

</span></p>
<span class="SousTitre">Activit&eacute;s de conditionnement physique<br></span>
<span class="Texte">
&nbsp;&nbsp;&nbsp;Activit&eacute;s aquatiques : <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	Jeux et chansons<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	Battements sur le ventre en utilisant un objet flottant, 2 m<br>
&nbsp;&nbsp;&nbsp;Nage d&#8217;endurance : <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	2 m<br>
</span></p>
<p><span class="SousTitre">Techniques et s&eacute;curit&eacute; aquatique</span><br>
<span class="Texte">
&nbsp;&nbsp;&nbsp;&#8226;	S&eacute;ance d&#8217;orientation sur l&#8217;&eacute;tablissement et supervision active <br>
&nbsp;&nbsp;&nbsp;&#8226;	Arr&ecirc;te! Regarde! Demande! (trouve l&#8217;adulte)<br>
&nbsp;&nbsp;&nbsp;&#8226;	Saut en eau &agrave; hauteur de la poitrine <br>
&nbsp;&nbsp;&nbsp;&#8226;	Le VFI et moi<br>
&nbsp;&nbsp;&nbsp;&#8226;	Objets flottants<br>
&nbsp;&nbsp;&nbsp;&#8226;	Maintien &agrave; la surface (avec aide) 5 secondes<br>
</span>
</p>

