<p><span class="SousTitre">Natation</span>
<span class="Texte"><br>
 &nbsp;&nbsp;&nbsp;Respirer :<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	Respiration rythm&eacute;e, 15 fois (sp&eacute;cifique au crawl)<br>
&nbsp;&nbsp;&nbsp;Glisser :<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	Combinaison de glissement sur le ventre/de c&ocirc;t&eacute; <br>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	Glissement sur le dos et battement des jambes avec rotation des &eacute;paules  3 x 10 m (en une le&ccedil;on)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	Crawl, 3 x 10 m (en une le&ccedil;on)</span></p>


<p><span class="SousTitre">Activit&eacute;s de conditionnement physique</span>
<span class="Texte"><br>
&nbsp;&nbsp;	Exercices de battement des jambes : <br>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	nage sur le dos 3 x 15 m <br>
&nbsp;&nbsp;	Nage d&#8217;endurance : <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	25 m</span></p>


<p><span class="SousTitre">Techniques et s&eacute;curit&eacute; aquatique</span>
<span class="Texte"><br>

&nbsp;&nbsp;	&#8226;	Auto s&eacute;curit&eacute;<br>
&nbsp;&nbsp;	&#8226;	Apprendre comment contacter le SMU<br>
&nbsp;&nbsp;	&#8226;	S&eacute;curit&eacute; prudente &#8211; plongeon s&eacute;curitaire<br>

&nbsp;&nbsp;	&#8226;	Entr&eacute;e qui d&eacute;sorientent<br>
&nbsp;&nbsp;	&#8226;	Plongeon accroupi<br>
&nbsp;&nbsp;	&#8226;	Maintien &agrave; la surface 45 sec. en eau profonde</span></p>

