<p><span class="Texte">Le cours de moniteur de sécurité aquatique (MSA) prépare les candidats à enseigner les programmes Croix-Rouge Natation. Les candidats se concentrent sur les stratégies permettant de créer et de développer des compétences en matière de sécurité aquatique et de natation dans les programmes « Croix-Rouge Natation préscolaire », « Croix-Rouge Natation junior » et « Aquadultes ». Ce cours :
&nbsp;&nbsp;&nbsp;• met l’accent sur la façon d’enseigner efficacement et d’évaluer les critères de performance;<br>
&nbsp;&nbsp;&nbsp;• permet d’appliquer les connaissances sur les compétences apprises lors du cours d’assistant moniteur de sécurité aquatique au contenu du programme Croix-Rouge Natation;<br>
&nbsp;&nbsp;&nbsp;• permet d’évaluer les aptitudes à enseigner les techniques d’intervention en cas d’urgence;<br>
&nbsp;&nbsp;&nbsp;• met l’accent sur le perfectionnement des techniques de nage, les exercices et les stratégies correctives;<br>
&nbsp;&nbsp;&nbsp;• permet aux moniteurs de mettre en pratique leurs aptitudes et leurs connaissances en matière d’enseignement.</span></p>

<p><span class="Texte">Ce cours permet au candidat d’être moniteur dans des cours de natation du programme de la Croix-Rouge.</span></p>

<p><span class="Texte">De façon générale ce cours s’offre à l’hiver, au printemps et à l’automne à raison de cours d’une durée de chacun.</span></p>

<p><span class="Texte">Ce cours s’offre au Cégep Lévis-Lauzon et au Cégep de Limoilou. Il s’offre aussi en session intensive à l’été au Cégep de Limoilou.</span></p>

<p><span class="Texte">Matériel suggéré ou obligatoire :<br>
&nbsp;&nbsp;&nbsp;• Maillot de bain<br>
&nbsp;&nbsp;&nbsp;• Bonet de bain<br>
&nbsp;&nbsp;&nbsp;• Papier et crayon<br>
&nbsp;&nbsp;&nbsp;• Manuel du moniteur de sécurité aquatique (inclus dans le prix du cours)</span></p>

<p><span class="Texte">Le candidat recevra une carte de compétence et un écusson du niveau par la poste environ 6 à 8 semaines après la réussite du cours.</span></p>
