<p><Span class="SousTitre">Natation</span><br>
<Span class="Texte">
&nbsp;&nbsp;&nbsp;•	Aller dans l’eau (avec aide)<br>
&nbsp;&nbsp;&nbsp;•	Immersion (optionnel)<br>
&nbsp;&nbsp;&nbsp;•	Initiation à la respiration rythmée; contrôle de la respiration (avec aide)<br>
&nbsp;&nbsp;&nbsp;•	Flottabilité et déplacement (avec aide)<br>
&nbsp;&nbsp;&nbsp;Mouvements : <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;•	Sur le ventre (avec aide)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;•	Sur le dos (avec aide)<br>
&nbsp;&nbsp;&nbsp;Flotter : <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;•	Flottaison sur le ventre avec redressement  (avec aide)<br>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;•	Flottaison sur le dos avec redressement (avec aide)<br>
</Span>
</p>
<p><Span class="SousTitre">Activités de conditionnement physique</span><br>
<Span class="Texte">
&nbsp;&nbsp;&nbsp;Activités aquatiques :<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;•	Jeux et chansons<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;•	Utilisation d’objets flottants comme soutien (avec aide)<br>
</Span>
</p>
<p><Span class="SousTitre">Techniques et sécurité aquatique</span><br>

<Span class="Texte">
&nbsp;&nbsp;&nbsp;•	Séance d’orientation sur l’établissement et supervision active <br>
&nbsp;&nbsp;&nbsp;•	Arrête! Regarde! Écoute!  <br>

&nbsp;&nbsp;&nbsp;•	Entrée et sortie en eau peu profonde (gardien d’enfant et enfant)<br>
&nbsp;&nbsp;&nbsp;•	Le VFI et moi (avec aide)<br>
&nbsp;&nbsp;&nbsp;•	Démontrer comment conserver sa chaleur<br>
&nbsp;&nbsp;&nbsp;•	Objets flottants<br>
&nbsp;&nbsp;&nbsp;•	Changement de direction (avec aide) <br>
&nbsp;&nbsp;&nbsp;•	Quand et comment obtenir de l’aide<br>
&nbsp;&nbsp;&nbsp;•	Prévention de suffocation<br>
&nbsp;&nbsp;&nbsp;•	Intervention en cas de suffocation<br>
</Span>
</p>

