<p><span class="SousTitre">Natation</span>
<span class=Texte><br>
 &nbsp;&nbsp;&nbsp;&#8226;	Respiration rythm&eacute;e, 15 fois (des deux c&ocirc;t&eacute;s)<br>
&nbsp;&nbsp;&nbsp;&#8226;	Crawl, 3 x 15 m (en une le&ccedil;on)<br>
&nbsp;&nbsp;&nbsp;&#8226;	Dos crawl&eacute;, 3 x 15 m (en une le&ccedil;on)<br>
&nbsp;&nbsp;&nbsp;&#8226;	Introduction au coup de pied fouett&eacute; sur le dos  3x5 m (en une le&ccedil;on)</span></p>
<p><span class="SousTitre">Activit&eacute;s de conditionnement physique</span>
<span class=Texte><br>
&nbsp;&nbsp;	Exercices de battement des jambes : <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	battement de dauphin 3 x 5 m<br>

&nbsp;&nbsp;	Nage d&#8217;endurance : <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	50 m</span></p>


<p><span class="SousTitre">Techniques et s&eacute;curit&eacute; aquatique</span>
<span class=Texte><br>
&nbsp;&nbsp;	&#8226;	Pour faire des activit&eacute;s nautiques en toute s&eacute;curit&eacute;<br>

&nbsp;&nbsp;	&#8226;	Rester au chaud<br>
&nbsp;&nbsp;	&#8226;	Aide/se pelotonner dans l&#8217;eau froide <br>
&nbsp;&nbsp;	&#8226;	Intro &agrave; la godille, en eau peu profonde<br>
&nbsp;&nbsp;	&#8226;	Maintien &agrave; la surface, 1 min.<br>

&nbsp;&nbsp;	&#8226;	Plongeon avec &eacute;lan</span></p>
