<p><span class="SousTitre">Natation</span>
<span class="Texte"><br>
 &nbsp;&nbsp;&nbsp;Respirer :<br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	respiration rythm&eacute;e, cinq fois<br>
&nbsp;&nbsp;&nbsp;Flotter :<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	Flottaison sur le ventre et redressement, 3 sec. , <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	Flottaison sur le dos et redressement, 3 sec.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	Flottaisons avec retournement, 6 sec. (avec aide)<br>

&nbsp;&nbsp;&nbsp;Glisser :  <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	Glissement sur le ventre, 3 sec.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	Glissement sur le ventre avec battement des jambes, 5 sec.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	Glissement sur le dos, 3 sec.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	Glissement sur le dos avec battement des jambes, 5 sec.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	Glissement avec retournement, 6 sec. (avec aide)<br>
</span>
</p>
<p><span class="SousTitre">Activit&eacute;s de conditionnement physique</span><br>
<span class="Texte">
&nbsp;&nbsp;	Exercices de battement des jambes :<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	battement alternatif des jambes, 10 m (avec aide)<br>
&nbsp;&nbsp;	Nage d&#8217;endurance : <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	5 m</p>
</span>
</p>

<p>

<span class="SousTitre">Techniques et s&eacute;curit&eacute; aquatique</span><br>
<span class="Texte">
&nbsp;&nbsp;	&#8226;	Orientation &agrave; l&#8217;installation et supervision <br>
&nbsp;&nbsp;	&#8226;	Secours m&eacute;dical d&#8217;urgence (SMU)<br>

&nbsp;&nbsp;	&#8226;	Entr&eacute;e/sortie en eau peu profonde<br>
&nbsp;&nbsp;	&#8226;	Immerger le visage dans l&#8217;eau<br>
&nbsp;&nbsp;	&#8226;	Expirer par la bouche ou le nez<br>
</span> 
</p>


