<p><span class="SousTitre">Natation</span>
<span class="Texte"> <br>
&nbsp;&nbsp;&nbsp;Respirer : <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	respiration rythm&eacute;e, dix fois (des deux c&ocirc;t&eacute;s)<br>
&nbsp;&nbsp;&nbsp;Flotter :<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	Flottaison sur le ventre, 5 sec.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	Flottaison sur le dos, 5 sec.<br>

&nbsp;&nbsp;&nbsp;Glisser :  <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	Glissement sur le ventre avec battement alternatif des jambes 3 x 5 m (en une le&ccedil;on)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	Glissement sur le dos avec battement alternatif des jambes 3 x 5 m (en une le&ccedil;on)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	Glissement sur le c&ocirc;t&eacute; avec battement alternatif des jambes, 3 m (avec aide)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	Glissement avec retournement et battement alternatif des jambes, 6sec.<br>
</span></p>


<p><span class="SousTitre">Activit&eacute;s de conditionnement physique</span>
<span class="Texte"> <br>
&nbsp;&nbsp;	Exercices de battement des 
jambes : <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	15 m (avec aide)<br>

&nbsp;&nbsp;	Nage d&#8217;endurance : <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	10 m</span></p>

<p><span class="SousTitre">Techniques et s&eacute;curit&eacute; aquatique</span>
<span class="Texte"> <br>
&nbsp;&nbsp;	&#8226;	R&egrave;glements du site<br>

&nbsp;&nbsp;	&#8226;	Intro au PFD/gilet de sauvetage<br>
&nbsp;&nbsp;	&#8226;	Transfert du poids &#8211; eau peu profonde<br>
&nbsp;&nbsp;	&#8226;	Activit&eacute; en eau profonde (avec aide)<br>
 
</span></p>

