<p><span class="SousTitre">Natation</span><br>
<span class="Texte">
&nbsp;&nbsp;&nbsp;&#8226;	Aller dans l&#8217;eau (avec aide)<br>
&nbsp;&nbsp;&nbsp;&#8226;	Techniques de soutien et de prise pour le gardien<br>
&nbsp;&nbsp;&nbsp;&#8226;	Immersion (optionnel)<br>
&nbsp;&nbsp;&nbsp;&#8226;	Initiation &agrave; la respiration rythm&eacute;e; contr&ocirc;le de la respiration (avec aide)<br>

&nbsp;&nbsp;&nbsp;&#8226;	Flottabilit&eacute; et d&eacute;placement (avec aide)<br>
&nbsp;&nbsp;&nbsp;Positions : <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	Position sur le ventre (avec aide)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	Position sur le dos (avec aide)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	Position verticale (avec aide)<br>

&nbsp;&nbsp;&nbsp;D&eacute;placements : <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	Sur le ventre (avec aide)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	Sur le dos (avec aide)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	Mouvement des bras (avec aide)</span></p>
<p><span class="SousTitre">Activit&eacute;s de conditionnement physique</span><br>
<span class="Texte">&nbsp;&nbsp;&nbsp;Activit&eacute;s aquatiques : <br>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	Jeux et chansons</span></p>

<p><span class="SousTitre">Techniques et s&eacute;curit&eacute; aquatique</span><br>
<span class="Texte">&nbsp;&nbsp;&nbsp;&#8226;	S&eacute;ance d&#8217;orientation sur l&#8217;&eacute;tablissement et supervision active <br>
&nbsp;&nbsp;&nbsp;&#8226;	Entr&eacute;e et sortie (gardien d&#8217;enfant et enfant)<br>

&nbsp;&nbsp;&nbsp;&#8226;	Montrer comment conserver sa chaleur<br>
&nbsp;&nbsp;&nbsp;&#8226;	Quand et comment obtenir de l&#8217;aide<br>
&nbsp;&nbsp;&nbsp;&#8226;	Pr&eacute;vention de suffocation<br>
</span></p>

