<p><span class="Texte">Le certificat Croix de bronze s’adresse aux candidats recherchant une formation plus poussée et désirant acquérir des notions de base en surveillance d’installations aquatiques. Ils y découvriront la différence entre le sauvetage et la surveillance, les principes à la base des procédures d’urgence et le travail d’équipe. Les candidats apprendront à porter secours à une victime blessée à la colonne vertébrale et une victime en arrêt cardiorespiratoire. La Croix de bronze est un préalable pour tous les autres programmes de formation avancés incluant les certificats Sauveteur national et Moniteur en sauvetage.</span></p>

<p><span class="Texte">Le cours de Croix de bronze permet à une personne dont le brevet est valide d’être assistant-surveillant-sauveteur sur une plage dès l’âge de 15 ans. Ce brevet a une validité de 2 ans. De plus, le cours de Croix de bronze permet à une personne dont le brevet est valide d’être surveillant-sauveteur d’une piscine d’hôtel, de restaurant, de camping et de bloc appartement dont les dimension sont inférieure à 150m carré dès l’âge de 16 ans.</span></p>

<p><span class="Texte">De façon générale ce cours s’offre à l’hiver, au printemps et à l’automne à raison de 8 cours d’une durée de 4h30 + l’examen. L’examen se déroule habituellement à la 9e semaine selon l’horaire habituel mais la date exacte sera connu au cours de la session.</span></p>

<p><span class="Texte">Ce cours s’offre aussi de façon intensive à l’été au Cégep de Limoilou.</span></p>

<p><span class="Texte">Il est offert à la piscine du Cégep Lévis-Lauzon et à la piscine du Cégep Limoilou.</span></p>

<p><span class="Texte">Matériel suggéré ou obligatoire :<br>
&nbsp;&nbsp;&nbsp;• Maillot de bain<br>
&nbsp;&nbsp;&nbsp;• Bonet de bain<br>
&nbsp;&nbsp;&nbsp;• Papier et crayon<br>
&nbsp;&nbsp;&nbsp;• Manuel canadien de sauvetage (même manuel qu’au Médaille de bronze)<br>
&nbsp;&nbsp;&nbsp;• T-Shirt*<br>
&nbsp;&nbsp;&nbsp;• Masque de poche *<br>
&nbsp;&nbsp;&nbsp;• Vêtements pouvant aller dans l’eau (le moniteur indiquera à quelle leçon      les candidats devront apporter ces vêtements long)</span></p>

<p><span class="Texte">* les items marqués d’un astérisque sont suggéré mais non obligatoire.</span></p>

<p><span class="Texte">Le candidat recevra une carte de compétence, un écusson et un pendentif du niveau par la poste environ 6 à 8 semaines après la réussite du cours.</span></p>
