<p><span class="SousTitre">Natation</span>
<span class="Texte"><br>
&nbsp;&nbsp;&nbsp;&#8226;	Crawl, 100 m <br>
&nbsp;&nbsp;&nbsp;&#8226;	Dos Crawl&eacute;, 100 m <br>
&nbsp;&nbsp;&nbsp;&#8226;	Dos &eacute;l&eacute;mentaire, 50 m<br>
&nbsp;&nbsp;&nbsp;&#8226;	Brasse, 3 x 25 m (en une le&ccedil;on)</span></p>

<span class="SousTitre">Activit&eacute;s de conditionnement physique</span>
<span class="Texte"><br>
&nbsp;&nbsp;		&laquo; Jambes mobiles &raquo;, seulement 3 min.<br>
&nbsp;&nbsp;		Styles de nage combo<br>

&nbsp;&nbsp;	Nage d&#8217;endurance : <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	400 m</span></p>


<p><span class="SousTitre">Techniques et s&eacute;curit&eacute; aquatique</span>
<span class="Texte"><br>
&nbsp;&nbsp;	&#8226;	Sage d&eacute;cision &#8211; influence des pairs<br>

&nbsp;&nbsp;	&#8226;	Complications li&eacute;es &agrave; la respiration artificielle<br>
&nbsp;&nbsp;	&#8226;	R&egrave;glements d&#8217;activit&eacute;s nautiques<br>
&nbsp;&nbsp;	&#8226;	Auto sauvetage &#8211; tomber &agrave; travers la glace<br>

&nbsp;&nbsp;	&#8226;	Plongeon de surface t&ecirc;te premi&egrave;re<br>
&nbsp;&nbsp;	&#8226;	Plongeon debout, eau peu profonde<br>
</span></p>

