<p><span class="Texte">Reconnu comme norme de performance du surveillant-sauveteur au Canada, le certificat Sauveteur national est conçu de façon à développer une compréhension approfondie des principes de surveillance, un bon jugement et une attitude responsable quant au rôle qu’assume le surveillant-sauveteur dans une installation aquatique. Le certificat vise à inculquer les principes et les processus décisionnels de sauvetage qui aideront les candidats à évaluer et à s’adapter aux diverses situations. Il comporte un tronc commun sur les principes et les techniques de surveillance et est composé d’éléments spécifiques reliés à l’environnement qui permettent aux candidats de se spécialiser dans l’une des quatre options que comporte ce certificat : piscine, plage contineatale, plage océanique et parc aquatique.</span></p>

<p><span class="Texte">Québec Natation offre le tronc commun du Sauveteur national uniquement avec l’option piscine. Québec Natation offre les options piscine et plage continentale.</span></p>

<p><img src=images/dottedline.png></p>

<p><span class=Titre>Sauveteur national option piscine</span><p>

<p><span class=SousTitre2>Pré requis : 16 ans + Croix de bronze + Premiers soins général<br>
(un cours de secourisme général d’une organisation reconnue par la Société de Sauvetage est également reconnu)</span></p>

<p><span class=Texte>De façon générale ce cours s’offre à l’hiver, au printemps et à l’automne à raison de 8 cours d’une durée de 5h00 + l’examen. L’examen se déroule habituellement à la 9e semaine selon l’horaire habituel mais la date exacte sera connu au cours de la session.</span><p>

<p><span class=Texte>Ce cours permet au candidat d’être surveillant sauveteur en piscine à partir de l’âge de 17 ans.</span><p>

<p><span class=Texte>Ce cours s’offre aussi de façon intensive à l’été au Cégep de Limoilou.</span><p>

<p><span class=Texte>Il est offert aux piscines du Cégep Lévis-Lauzon, du Cégep Limoilou et du Cégep Ste-Foy.</span><p>

<p><span class=Texte>Matériel suggéré ou obligatoire :<br>
&nbsp;&nbsp;&nbsp;• Maillot de bain<br>
&nbsp;&nbsp;&nbsp;• Bonet de bain<br>
&nbsp;&nbsp;&nbsp;• Papier et crayon<br>
&nbsp;&nbsp;&nbsp;• Manuel Alerte (inclus dans le prix)<br>
&nbsp;&nbsp;&nbsp;• Manuel Soins d’urgence en milieu aquatique (même que dans Premiers soins général)<br>
&nbsp;&nbsp;&nbsp;• Manuel Soins immédiat de la FQMC (même que dans Premiers soins général)<br>
&nbsp;&nbsp;&nbsp;• Réglementation sur les bains public S-3,r.3 *<br>
&nbsp;&nbsp;&nbsp;• T-Shirt<br>
&nbsp;&nbsp;&nbsp;• Masque de poche *<br>
&nbsp;&nbsp;&nbsp;• Sifflet (idéalement Fox 40 ou mini Fox40)</span></p>

<p><span class=Texte>* les items marqués d’un astérisque sont suggéré mais non obligatoire</span></p>

<p><span class=Texte>Le candidat recevra une carte de compétence et un écusson du niveau par la poste environ 6 à 8 semaines après la réussite du cours.</span></p>

<p><img src=images/dottedline.png></p>

<p><span class=Titre>Sauveteur national option plage</span><p>

<p><span class=SousTitre2>Pré requis : 16 ans + sauveteur national option piscine</span><p>

<p><span class=Texte>Ce cours permet d’être surveillant-sauveteur plage à partir de l’âge de 17 ans.</span><p>

<p><span class=Texte>De façon générale, ce cours s’offre uniquement en juin. Le cours se déroule de façon intensive soit une fin de semaine complète en plage + une soirée de théorie qui se déroule dans la semaine précédante.</span><p>

<p><span class=Texte>La formation en plage s’offre au Lac St-Joseph et/ou au Lac-Beauport. La formation théorique s’offre au Cégep de Limoilou.</span><p>

<p><span class=Texte>Matériel suggéré ou obligatoire :<br>
&nbsp;&nbsp;&nbsp;• Maillot de bain<br>
&nbsp;&nbsp;&nbsp;• Bonnet de bain en plastique ou en silicone *<br>
&nbsp;&nbsp;&nbsp;• Papier et crayon<br>
&nbsp;&nbsp;&nbsp;• Manuel Alerte (même que dans Sauveteur national opt. Piscine)<br>
&nbsp;&nbsp;&nbsp;• Manuel Soins d’urgence en milieu aquatique (même que dans Premiers soins général)<br>
&nbsp;&nbsp;&nbsp;• Manuel Soins immédiat de la FQMC (même que dans Premiers soins général)<br>
&nbsp;&nbsp;&nbsp;• Réglementation sur les bains public S-3,r.3 *<br>
&nbsp;&nbsp;&nbsp;• Masque de poche *<br>
&nbsp;&nbsp;&nbsp;• Sifflet (idéalement Fox 40 ou mini Fox40)<br>
&nbsp;&nbsp;&nbsp;• Combinaison isothermique (wet suit)*<br>
&nbsp;&nbsp;&nbsp;• Palmes, masque et tuba<br>
&nbsp;&nbsp;&nbsp;• Couverture chaude *<br>
&nbsp;&nbsp;&nbsp;• Crème solaire *<br>
&nbsp;&nbsp;&nbsp;• Huile à moustique *<br>
&nbsp;&nbsp;&nbsp;• Vêtements chauds*<br>
&nbsp;&nbsp;&nbsp;• Serviettes (plusieurs)*<br>
&nbsp;&nbsp;&nbsp;• Collations*</span></p>

<p><span class=Texte>*les items marqués d’un astérisque sont suggéré mais non obligatoire</span><p>


<p><span class=Texte>PRENDRE NOTE :<br>
Le cours de Sauveteur national option plage s’offre au mois de juin dans un lac… l’eau est rarement chaude et le cours ne peut pas être annulé en raison des conditions climatiques. Il est donc important que le candidat soit en mesure de faire face à différentes conditions. Il est préférable d’avoir plus de matériel que d’en manquer. Les moniteurs, lors du cours théorique, donneront une liste d’équipement que les candidats ont généralement à la maison et qui peut servir.</span><p>

<p><span class=Texte>Le candidat recevra une carte de compétence et un écusson du niveau par la poste environ 6 à 8 semaines après la réussite du cours.</span><p>
