<p><h4 class=futura>AquAdulte - Essentiels 2</h4></p>

<span class="SousTitre">Objectifs</span>
<span class="Texte"><br>
&nbsp;&nbsp;&nbsp;&#8226; 	D&eacute;velopper un ou plusieurs styles de nage en se concentrant sur l&#8217;am&eacute;lioration de la force et de l'endurance.<br>

&nbsp;&nbsp;&nbsp;&#8226; 	Introduire ou approfondir des connaissances et habilet&eacute;s en mati&egrave;re de s&eacute;curit&eacute; aquatique pertinentes pour l&#8217;&eacute;l&egrave;ve.</span></p>

<span class="SousTitre">Aper&ccedil;u du programme</span>

<span class="Texte"><br>

&nbsp;&nbsp;&nbsp;&#8226; 		Le style de nage doit &ecirc;tre choisi de concert avec le moniteur et &ecirc;tre &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;d&eacute;velopp&eacute; selon les crit&egrave;res de progression et de performance du programme Croix Rouge Natation junior.<br>
&nbsp;&nbsp;&nbsp;&#8226;	S&eacute;curit&eacute; aquatique de base (si elle n&#8217;a pas d&eacute;j&agrave; &eacute;t&eacute; couverte).<br>

&nbsp;&nbsp;&nbsp;&#8226;	Modules de s&eacute;curit&eacute; aquatique, tels qu&#8217;indiqu&eacute;s sur la fiche d&#8217;apprentissage de l&#8217;&eacute;l&egrave;ve. <br>
&nbsp;&nbsp;&nbsp;&#8226;	Les moniteurs consultent leurs &eacute;l&egrave;ves pour d&eacute;terminer les buts et les priorit&eacute;s d&#8217;apprentissage.<br>

<br>
</p>

