<p><span class="Texte">L’Étoile de bronze est le premier certificat de niveau bronze. Les participants sont initiés au sauvetage en apprenant à trouver des solutions à divers problèmes et à prendre des décisions en tant qu’individu et en tant que membre d’une équipe. Ils apprennent la réanimation cardiorespiratoire (RCR) ainsi que les habiletés de sauvetage nécessaires pour devenir leur propre sauveteur au besoin.</span></p>

<p><span class="Texte">L’Étoile de bronze est une excellente option pour un jeune ayant terminé ses niveaux de natation, mais qui n’a pas encore l’âge requis pour faire sa Médaille de bronze. De plus, il permet de faire une transition plus en douceur entre un cours de natation régulier (8 x 45 min) et les cours de formation (8 à 10 sem : 3h30 à 5h00 par cours).</span></p>

<p><span class="Texte">De façon général ce cours s’offre à l’hiver, au printemps et à l’automne à raison de 8 cours d’une durée de 1h30.</span></p>

<p><span class="Texte">Il est offert à la piscine du Cégep Lévis-Lauzon et à la piscine du Cégep Limoilou.</span></p>

<p><span class="Texte">Matériel suggéré ou obligatoire :<br>
&nbsp;&nbsp;&nbsp;• Maillot de bain<br>
&nbsp;&nbsp;&nbsp;• Bonet de bain<br>
&nbsp;&nbsp;&nbsp;• T-Shirt*<br>
&nbsp;&nbsp;&nbsp;• Masque de poche *<br>
&nbsp;&nbsp;&nbsp;• Vêtements pouvant aller dans l’eau (le moniteur indiquera à quelle leçon les candidats devront apporter ces vêtements long)</span></p>

<p><span class="Texte">* les items marqués d’un astérisque sont suggéré mais non obligatoire
Le candidat recevra une carte de compétence, un écusson et un pendentif du niveau par la poste environ 6 à 8 semaines après la réussite du cours.</span></p>

<p><span class="Texte">Ce cours permet de passer directement au niveau Médaille de bronze et ce, même s’il n’a pas l’âge requis.</span></p>
