<p><span class="SousTitre">Natation</span>
<span class="Texte"><br>
 &nbsp;&nbsp;&nbsp;Respirer : <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	Respiration rythm&eacute;e, 15 fois<br>
&nbsp;&nbsp;&nbsp;Glisser :  <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	Glissement sur le ventre avec battement alternatif des jambes 3 x 10 m (en une le&ccedil;on)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	Glissement sur le dos avec battement alternatif des jambes 3 x 10 m (en une le&ccedil;on)<br>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	Glissement sur le c&ocirc;t&eacute; avec battement alternatif des jambes, 5 sec.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	Combinaison de glissement sur le ventre/de c&ocirc;t&eacute; <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	Crawl, 3 x 5 m</span></p>

<span class="SousTitre">Activit&eacute;s de conditionnement physique</span>
<span class="Texte"><br>
&nbsp;&nbsp;	Exercices de battement des jambes : <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	3 x 15 m <br>
&nbsp;&nbsp;	Nage d&#8217;endurance : <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	15 m</span></p>


<p>
<span class="SousTitre">Techniques et s&eacute;curit&eacute; aquatique</span>
<span class="Texte"><br>
&nbsp;&nbsp;	&#8226;	Quand et o&ugrave; nager<br>
&nbsp;&nbsp;	&#8226;	Transfert du poids &#8211; eau peu profonde<br>
&nbsp;&nbsp;	&#8226;	Flottaison en eau profonde, 5 sec.<br>
&nbsp;&nbsp;	&#8226;	Changement de direction, eau profonde<br>
&nbsp;&nbsp;	&#8226;	Maintien &agrave; la surface, 20 sec., eau profonde<br>
&nbsp;&nbsp;	&#8226;	Plongeon en position assise<br>
</span></p>

