<p><span class="Texte">Le cours d’assistant moniteur de sécurité aquatique (MASA) présente aux candidats des notions de base en pédagogie en ciblant les connaissances théoriques qui soutiennent l’apprentissage et l’enseignement. Cette formation transmet les connaissances et les aptitudes pour devenir assistant moniteur de sécurité aquatique en mettant l’accent sur les méthodes d’enseignement, les styles d’apprentissage, les capacités physiques, les progressions, la communication, la supervision sécuritaire et la rétroaction. Les candidats ont également l’occasion de démontrer et de faire évaluer leur compréhension des connaissances et des aptitudes lors d’un stage pratique d’enseignement de huit heures et par des travaux pratiques individuels.</span></p>

<p><span class="Texte">Ce cours permet au candidat d’être assistant moniteur dans des cours de natation du programme de la Croix-Rouge.</span></p>


<p><span class="Texte">De façon générale ce cours s’offre à l’hiver, au printemps et à l’automne à raison de 8 cours d’une durée de 4h00 chacun.</span></p>

<p><span class="Texte">Ce cours s’offre au Cégep Lévis-Lauzon et au Cégep de Limoilou. Il s’offre aussi en session intensive à l’été au Cégep de Limoilou.</span></p>

<p><span class="Texte">Matériel suggéré ou obligatoire :<br>
&nbsp;&nbsp;&nbsp;• Maillot de bain<br>
&nbsp;&nbsp;&nbsp;• Bonet de bain<br>
&nbsp;&nbsp;&nbsp;• Papier et crayon<br>
&nbsp;&nbsp;&nbsp;• Tableau des styles de nages (inclus dans le prix du cours)<br>
&nbsp;&nbsp;&nbsp;• Relieur à feuilles mobiles, Guide d’assistant moniteur de sécurité aquatique (inclus dans le prix du cours) De plus, un CD-ROM incluant des plans de cours pour tous les niveaux du programme est inclus.<br>
&nbsp;&nbsp;&nbsp;• Guide du cours – MASA (inclus dans le prix)<br>
&nbsp;&nbsp;&nbsp;• Une photocopie d’une preuve d’âge et de la carte Croix de bronze devront être remis à l’instructeur SA au cours de la session afin que le candidat puisse recevoir sa certification.</span></p>

<p><span class="Texte">Le candidat recevra une carte de compétence et un écusson du niveau par la poste environ 6 à 8 semaines après la réussite du cours.</span></p>
