<p><h4 class=futura>Aquaforme</h4>
<span class="Texte"><br>

Conditionnement physique en piscine, en eau peu profonde, l’Aquaforme s’adresse aux adultes de tous âges et de toute condition physique.* Que vous ayez 20 ans, 75 ans, que vous soyez un homme, une femme, un programme d’aquaforme pourra vous aider à améliorer ou maintenir votre condition physique. Chacun va à son rythme. Nos moniteurs et monitrices dynamiques sauront vous faire bouger. L’Aquaforme est efficace tant au niveau cardio-vasculaire, au niveau de la musculation (abdominaux, jambes, bras, dos) et de la souplesse. Un gros avantage … il y a peu de choc sur les articulations des chevilles et des genoux puisque que votre poid est supporté par l’eau.<br>
<br>
*Il n’est pas nécessaire de savoir nager, mais si vous avez peur de l’eau ou si vous paniquez lorsque vous recevez de l’eau dans le visage, il serait préférable de suivre un cours Aquadultes au préalable.</span></p>

<p><span class="Titre">Aquajogging</span><span class="Texte"><br>

Conditionnement physique en piscine, en eau profonde, l’Aquaforme s’adresse aux adultes de tous âges et de toute condition physique.* Afin de vous maintenir à la surface, vous aurez à porter une ceinture Aquajogger. Cette ceinture de flotaison ne limite en rien vos mouvements et vous aide à flotter en position debout. Un programme d’aquajogging pourra vous aider à améliorer ou maintenir votre condition physique. Chacun va à son rythme. Nos moniteurs et monitrices dynamiques sauront vous faire bouger. L’Aquajogging est efficace tant au niveau cardio-vasculaire, au niveau de la musculation (abdominaux, jambes bras et autres) et de la souplesse. Un gros avantage … il n’y a pas de choc sur les articulations des chevilles et des genoux puisque que votre poid est supporté par l’eau.<br>
<br>
*Puisque ce cours se passe en eau profonde, il est nécessaire que vous sachiez nager pour vous inscrire pour des questions de sécurité et ce même si l’activité se fait avec une ceinture Aquajogger qui flotte.</span></p>
