<p><span class="SousTitre">Natation</span>
<span class="Texte"><br>
 &nbsp;&nbsp;&nbsp;&#8226;	Crawl, 50 m (en une le&ccedil;on)<br>
&nbsp;&nbsp;&nbsp;&#8226;	Dos crawl&eacute;, 50 m (en une le&ccedil;on)<br>
&nbsp;&nbsp;&nbsp;&#8226;	Dos &eacute;l&eacute;mentaire, 3 x 25 m (en une le&ccedil;on)<br>

&nbsp;&nbsp;&nbsp;&#8226;	Godille sur le ventre 3 x 5 m (en une le&ccedil;on)<br>
&nbsp;&nbsp;&nbsp;&#8226;	Coup de pied fouett&eacute; sur le ventre, bras allong&eacute;s, 3 x 15 m (en une le&ccedil;on)</span></p>

<span class="SousTitre">Activit&eacute;s de conditionnement physique</span>
<span class="Texte"><br>

&nbsp;&nbsp;	R&eacute;trop&eacute;dalage/nage debout fixe, 3 min.<br>

&nbsp;&nbsp;	Nage d&#8217;endurance : <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	150 m</p>

<p><span class="SousTitre">Techniques et s&eacute;curit&eacute; aquatique</span>
<span class="Texte"><br>
&nbsp;&nbsp;	&#8226;	Obstruction partielle et compl&egrave;te<br>
&nbsp;&nbsp;	&#8226;	Porter secours en cas de suffocation &#8211; personne consciente<br>
&nbsp;&nbsp;	&#8226;	Objets &agrave; lancer avec aide<br>

&nbsp;&nbsp;	&#8226;	Objets &agrave; tendre avec aide <br>
&nbsp;&nbsp;	&#8226;	Godille sur le dos t&ecirc;te premi&egrave;re, 10 m
</span></p>

