<p><span class="SousTitre">Natation</span><br>
<span class="Texte">
 &nbsp;&nbsp;&nbsp;•	Aller dans l’eau (avec aide)<br>
&nbsp;&nbsp;&nbsp;•	Initiation à la respiration rythmée; contrôle de la respiration<br>
&nbsp;&nbsp;&nbsp;•	Flottabilité et déplacement (avec aide)<br>
&nbsp;&nbsp;&nbsp;•	Déplacement en eau peu profonde<br>
&nbsp;&nbsp;&nbsp;Flotter :<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;•	Flottaison sur le ventre avec redressement 3 sec. (avec aide)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;•	Flottaison sur le dos avec redressement 3 sec. (avec aide)<br>
&nbsp;&nbsp;&nbsp;Glisser :<br>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;• sur le ventre/dos avec redressement (avec aide)<br>
&nbsp;&nbsp;&nbsp;Nager : <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;•	Battement de base des jambes sur le ventre  (avec aide)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;•	Nage sur le ventre (avec aide)<br>
</span>
</p>
<p><span class="SousTitre">Activités de conditionnement physique</span><br>
<span class="Texte">&nbsp;&nbsp;&nbsp;Activités aquatiques : <br>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;	•	Jeux et chansons<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;	•	Battements des jambes sur le ventre en utilisant un objet flottant  2 m &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;	&nbsp;	(avec aide)<br>
</span>
</p>
<p><span class="SousTitre">Techniques et sécurité aquatique</span><br>
<span class="Texte">
&nbsp;&nbsp;&nbsp;•	Séance d’orientation sur l’établissement et supervision active <br>
&nbsp;&nbsp;&nbsp;•	Arrête! Regarde! Demande! (trouve l’adulte)<br>
&nbsp;&nbsp;&nbsp;•	Entrée et sortie (avec aide)<br>
&nbsp;&nbsp;&nbsp;•	Saut en eau à hauteur de la poitrine (avec aide)<br>
&nbsp;&nbsp;&nbsp;•	Saut en eau à hauteur de la poitrine (avec aide)<br>
&nbsp;&nbsp;&nbsp;•	Le VFI et moi (avec aide)<br>
</span>
</p>

