<p><span class="Texte">Le certificat Médaille de bronze permet aux candidats d’acquérir une compréhension des quatre composantes de base du sauvetage : le jugement, les connaissances, les habiletés et la forme physique. Ils apprennent les techniques de remorquage et de portage, de défenses et de dégagements, afin de se préparer à effectuer des sauvetages de victimes conscientes et inconscientes en prenant des risques de plus en plus élevés. Les candidats développent une meilleure technique de nage et améliorent leur endurance. La médaille de bronze est préalable pour le certificat Croix de bronze.</span></p>

<p><span class="Texte">Le cours de Médaille de bronze permet à une personne dont le brevet est valide d’être assistant-surveillant-sauveteur sur le bord d’une piscine dès l’âge de 15 ans. Ce brevet a une validité de 2 ans.</span></p>

<p><span class="Texte">De façon générale ce cours s’offre à l’hiver, au printemps et à l’automne à raison de 8 cours d’une durée de 3h30 + l’examen. L’examen se déroule habituellement à la 9e semaine selon l’horaire habituel mais la date exacte sera connu au cours de la session.</span></p>

<p><span class="Texte">Ce cours s’offre aussi de façon intensive à l’été au Cégep de Limoilou.</span></p>

<p><span class="Texte">Il est possible d’effectuer le cours de Médaille de bronze combiné au cours de Croix de bronze.</span></p>

<p><span class="Texte">Il est offert à la piscine du Cégep Lévis-Lauzon et à la piscine du Cégep Limoilou.</span></p>

<p><span class="Texte">Matériel suggéré ou obligatoire :<br>
&nbsp;&nbsp;&nbsp;• Maillot de bain<br>
&nbsp;&nbsp;&nbsp;• Bonet de bain<br>
&nbsp;&nbsp;&nbsp;• Papier et crayon<br>
&nbsp;&nbsp;&nbsp;• Manuel canadien de sauvetage (inclus dans le prix du cours)<br>
&nbsp;&nbsp;&nbsp;• T-Shirt*<br>
&nbsp;&nbsp;&nbsp;• Masque de poche *<br>
&nbsp;&nbsp;&nbsp;• Vêtements pouvant aller dans l’eau (le moniteur indiquera à quelle leçon      les candidats devront apporter ces vêtements long)</span></p>

<p><span class="Texte">* les items marqués d’un astérisque sont suggéré mais non obligatoire.</span></p>

<p><span class="Texte">Le candidat recevra une carte de compétence, un écusson et un pendentif du niveau par la poste environ 6 à 8 semaines après la réussite du cours </span></p>
