<p><span class="Texte">Le cours Premiers soins général prépare le candidat à assumer un rôle d’intervenant médical lors d’une situation d’urgence demandant des notions de premiers soins particulières. Le candidat devra entre autre prodiguer des traitements spécifiques afin d’immobiliser une blessure tout en attendant les secours médicaux d’urgence.</span></p>

<p><span class="Texte">Le cours Premiers soins général prépare également le candidat à assumer une rôle de prévention en lui permettant de reconnaître rapidement des signes et symptômes anormaux et d’appliquer les mesures nécessaires.</span></p>

<p><span class="Texte">Ce cours s’offre de façon intensive sur deux jours. Il sera disponible à toutes les sessions.</span></p>

<p><span class="Texte">Il est offert à la piscine du Cégep Lévis-Lauzon et à la piscine du Cégep Limoilou.</span></p>

<p><span class="Texte">Matériel suggéré ou obligatoire :<br>
&nbsp;&nbsp;&nbsp;• Maillot de bain<br>
&nbsp;&nbsp;&nbsp;• Bonet de bain<br>
&nbsp;&nbsp;&nbsp;• Papier et crayon<br>
&nbsp;&nbsp;&nbsp;• Manuel canadien de sauvetage (même manuel qu’au Médaille de bronze)<br>
&nbsp;&nbsp;&nbsp;• Manuel Soins d’urgence en milieu aquatique (inclus dans le prix)<br>
&nbsp;&nbsp;&nbsp;• Manuel Soins immédiat de la FQMC (inclus dans le prix)<br>
&nbsp;&nbsp;&nbsp;• T-Shirt*<br>
&nbsp;&nbsp;&nbsp;• Masque de poche *<br>
&nbsp;&nbsp;&nbsp;• Vêtements pouvant être tachés. (Les candidats auront des mises en situation comportant du maquillage (faux sang et autre))</span></p>

<p><span class="Texte">* les items marqués d’un astérisque sont suggéré mais non obligatoire</span></p>

<p><span class="Texte">Le candidat recevra une carte de compétence par la poste environ 6 à 8 semaines après la réussite du cours.</span></p>
