<p><span class="SousTitre">Natation</span><br>
<span class="Texte">
&nbsp;&nbsp;&nbsp;&#8226;	Respiration rythm&eacute;e, dix fois (des deux c&ocirc;t&eacute;s)<br>
&nbsp;&nbsp;&nbsp;Glisser : <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	Glissement sur le ventre avec battement des jambes,  3x5 m<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	Glissement sur le dos avec battement des jambes,  3x5 m<br>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	Glissement sur le c&ocirc;t&eacute; avec battement des jambes, 5 m<br>
&nbsp;&nbsp;&nbsp;Nager : <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	Nage sur le ventre, 7 m<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	Nage sur le dos, 7 m<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	Nage continue, 10 m<br>
</span>
</p>
<span class="SousTitre">Activit&eacute;s de conditionnement physique</span><br>
<span class="Texte">
&nbsp;&nbsp;	Activit&eacute;s aquatiques : <br>
&nbsp;&nbsp;	&nbsp;&nbsp;	&#8226;	Introduction &agrave; la nage synchronis&eacute;e (pirouettes, baignoire et flottaison) <br>

&nbsp;&nbsp;	&nbsp;&nbsp;	&#8226;	Activit&eacute;s de relais <br>
&nbsp;&nbsp;	Exercices de battement des 
jambes : <br>
&nbsp;&nbsp;	&nbsp;&nbsp;	&#8226;	2x10 m<br>
&nbsp;&nbsp;	&nbsp;&nbsp;	&#8226;		battement de baleine (plus fort que le battement de dauphin)<br>

&nbsp;&nbsp;		Nage d&#8217;endurance :<br>
&nbsp;&nbsp;	&nbsp;&nbsp;	&#8226;	 2x10 m
</span>
</p>
<p><span class="SousTitre">Techniques et s&eacute;curit&eacute; aquatique</span><br>
<span class="Texte">
&nbsp;&nbsp;	&#8226;	S&eacute;ance d&#8217;orientation sur     l&#8217;&eacute;tablissement et supervision active <br>

&nbsp;&nbsp;	&#8226;	Quand et o&ugrave; nager<br>
&nbsp;&nbsp;	&#8226;	Arr&ecirc;te! Regarde! Demande!<br>
&nbsp;&nbsp;	&#8226;	Changement de direction en eau peu profonde<br>
&nbsp;&nbsp;	&#8226;	Maintien &agrave; la surface, 20 sec.<br>
&nbsp;&nbsp;	&#8226;	Saut en eau profonde, maintien &agrave; la surface 20 sec<br>
&nbsp;&nbsp;	&#8226;	Arr&ecirc;te! Lance! Demande de l&#8217;aide!  Objets<br>
</span>
</p>

