<p><span class="SousTitre">Natation</span>
<span class="Texte"><br>
&nbsp;&nbsp;&nbsp;&#8226;	Crawl, 75 m <br>
&nbsp;&nbsp;&nbsp;&#8226;	Dos crawl&eacute;, 75 m <br>
&nbsp;&nbsp;&nbsp;&#8226;	Dos &eacute;l&eacute;mentaire, 50 m<br>
&nbsp;&nbsp;&nbsp;&#8226;	Brasse, 3 x 25 m (en une le&ccedil;on)</span></p>

<p><span class="SousTitre">Activit&eacute;s de conditionnement physique</span>
<span class="Texte"><br>
&nbsp;&nbsp;	Exercices de battement des jambes :<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	R&eacute;trop&eacute;dalage/nage debout,  3 min.<br>
&nbsp;&nbsp;	Exercices de battement du dauphin, 3 x 10 m&nbsp;&nbsp;	<br>
&nbsp;&nbsp;	Nage d&#8217;endurance : <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#8226;	300 m</span></p>


<p><span class="SousTitre">Techniques et s&eacute;curit&eacute; aquatique</span>
<span class="Texte"><br>
&nbsp;&nbsp;	&#8226;	Hypothermie<br>

&nbsp;&nbsp;	&#8226;	Dangers en eaux libres<br>
&nbsp;&nbsp;	&#8226;	Respiration artificielle, adulte et enfant<br>
&nbsp;&nbsp;	&#8226;	Plongeon de surface, les  pieds en premier<br>
&nbsp;&nbsp;	&#8226;	Saut d&#8217;arr&ecirc;t<br>

</span></p>

