<p><h4 class=futura>AquAdulte - Essentiels 1</h4></p>

<p><span class="SousTitre">Objectifs</span>
<span class="Texte"><br>
&nbsp;&nbsp;&nbsp;&#8226; D&eacute;velopper l&#8217;aisance dans l&#8217;eau par l&#8217;interm&eacute;diaire de la flottaison de <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;base, des techniques de mouvement et de respiration. <br>
&nbsp;&nbsp;&nbsp;&#8226; Approfondir les connaissances de base, techniques et attitudes <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;n&eacute;cessaires pour pr&eacute;parer, rester en s&eacute;curit&eacute; et survivre dans l&#8217;eau, sur &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;l&#8217;eau et pr&egrave;s de l&#8217;eau.
</span></p>


<p><span class="SousTitre">Aper&ccedil;u du programme</span>
<span class="Texte"><br>
&nbsp;&nbsp;&nbsp;&#8226; 	Techniques de nage de base similaires aux niveaux 1-4 du programme &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Croix-Rouge Natation junior, en travaillant sur la performance avec et sans &nbsp;aide. <br>
&nbsp;&nbsp; &#8226;	S&eacute;curit&eacute; aquatique de base (p. ex. pr&eacute;paration aux activit&eacute;s aquatiques,&nbsp;d&eacute;terminer des moyens pour rester en s&eacute;curit&eacute;, entrer dans l&#8217;eau en toute s&eacute;curit&eacute;, gilets de sauvetage/VFI), changement de direction, maintien &agrave; la surface, objets &agrave; tendre ou &agrave; lancer).<br>

&nbsp;&nbsp;&nbsp;&#8226;	Modules de s&eacute;curit&eacute; aquatique, tel qu&#8217;indiqu&eacute; sur la fiche d&#8217;apprentissage de l&#8217;&eacute;l&egrave;ve  </span>
</p>

