<h4 class=futura>Crocrodile</h4>
<p><span class=Texte><b>Âge:</b> 3 ans à 5 ans<br>
Les enfants d’âge préscolaire commencent à effectuer des glissements et des battements de jambes dans l’eau profonde de façon indépendante. Ils développent leur endurance en augmentant les distances de nage sur le ventre et sur le dos. Les participants apprennent le battement de jambes du dauphin et essaient les techniques de synchronisation dans l’eau.
</span></p>
