<h4 class=futura>Tortue de mer</h4>
<p><span class=Texte><b>Âge:</b> 24 mois à 36 mois avec participation parentale<br>
Un niveau de transition pour les enfants d’âge préscolaire et leurs parents. Les parents peuvent transférer graduellement leur enfant aux soins du moniteur, ou, niveau d’entrée au programme pour les enfants de 3 à 5 ans qui n’ont suivi aucun cours de natation auparavant. Ce niveau est axé sur le développement des techniques de nage, les glissements et la flottaison, ainsi que sur l’initiation à l’eau profonde et aux entrées sécuritaires.
</span></p>
