<h4 class=futura>Junior - Niveau 7</h4>
<p><span class=Texte>Le niveau 7 continue d’approfondir les techniques et l’endurance pour le crawl, le dos crawlé et le dos élémentaire et introduit le coup de pied fouetté sur le ventre. Les enfants apprennent à reconnaître les obstructions partielles ou complètes des voies respiratoires et augmentent leur endurance en participant à des périodes de nage debout chronométrées et en nageant sur une distance de 150 mètres.
</span></p>
