<h4 class=futura>Junior - Niveau 6</h4>
<p><span class=Texte>Le crawl et le dos crawlé continuent d’être approfondis et le dos élémentaire est introduit. Les enfants sont également initiés à la sécurité sur la glace, au sauvetage élémentaire d’une personne en lançant un objet à lancer, à la nage debout et au plongeon tête première. L’endurance est augmentée en nageant sur une distance de 75 mètres.
</span></p>
