<h4 class=futura>Baleine</h4>
<p><span class=Texte><b>Âge:</b> 3 ans à 5 ans<br>
Au niveau Baleine, les enfants apprendront à nager de façon indépendante et à participer à des jeux d’équipe. Les enfants d’âge préscolaire augmenteront et amélioreront leurs techniques de nage sur le ventre et sur le dos. Ils apprendront également à lancer des objets à lancer pour venir en aide à une autre personne dans l’eau.
</span></p>
