<h4 class=futura>Junior - Niveau 9</h4>
<p><span class=Texte>Le crawl, le dos crawlé, le dos élémentaire et la brasse continuent d’être approfondis. Dans ce niveau, on encourage les enfants à essayer les combinaisons des différentes techniques de nage et de coups de pieds pour optimiser leur forme physique. Ils travaillent également le plongeon de surface tête première et le plongeon debout; ils apprennent à faire des choix sensés, à reconnaître l’influence de leurs camarades et l’autosauvetage sur glace. L’endurance est augmentée en nageant sur une distance de 400 mètres.
</span></p>
