<h4 class=futura>Poisson-Lune</h4>
<p><span class=Texte><b>Âge:</b> 3 ans à 5 ans<br>
À ce niveau, les enfants apprennent à nager de façon de plus en plus indépendante en se délaissant petit à petit de leur ballon.  Ils apprennent donc à pratiquer leur glissement, flottaison et habiletés de natation sans aide, par le biais de jeux et de chansons. Ils commenceront à s’habituer à l’eau profonde.
</span></p>
