<h4 class=futura>Étoile de mer</h4>
<p><span class=Texte><b>Âge:</b> 4 mois à 12 mois<br>
Une classe d’initiation pour les nourrissons et leur parent ou la personne responsable. Pour être inscrit à ce niveau, les nourrissons doivent être capables de lever la tête sans aide. Cette classe d’initiation à l’eau vise à faire découvrir la flottabilité, le mouvement, l’entrée dans l’eau, ainsi que des chansons et des jeux dans l’eau.

</span></p>
