<h4 class=futura>Junior - Niveau 4</h4>
<p><span class=Texte>Le crawl, le glissement arrière et le roulement d’épaule du dos crawlé sont approfondis. Les enfants travaillent les plongeons de départ à genoux et le maintien à la surface et développent un sens accru de leur propre sécurité en prenant conscience de leurs limites. L’endurance est augmentée en nageant sur une distance de 25 mètres.
</span></p>
