<h4 class=futura>Junior - Niveau 3</h4>
<p><span class=Texte>Ce niveau est une introduction au crawl, ainsi qu’aux critères de base pour déterminer quand et où se baigner. Le plongeon est introduit et les enfants commencent à travailler la flottaison et les changements de direction. L’endurance est augmentée en gagnant de la force grâce aux battements alternatifs de base des jambes et en nageant sur une distance de 15 mètres.
</span></p>
