<h4 class=futura>Junior - Niveau 10</h4>
<p><span class=Texte>Les techniques de nage acquises sont approfondies; les nageurs sont initiés au papillon et au battement de jambes en ciseaux comme technique de réchauffement/récupération pour la mise en forme. Les enfants apprennent les dangers de l’exposition à la chaleur/au soleil, le sauvetage sur glace et les plongeons en surface tête première et pieds premiers. L’endurance est augmentée grâce au battement de jambes du dauphin, aux exercices de papillon et en nageant sur une distance de 500 mètres.
</span></p>
