<h4 class=futura>Junior - Niveau 8</h4>
<p><span class=Texte>Le niveau 8 est une introduction à la brasse, au plongeon de surface pieds premiers et aux entrées de sauvetage. Les enfants sont sensibilisés aux dangers de l’eau libre et de l’hypothermie; ils apprennent comment administrer la respiration artificielle aux enfants et aux adultes. L’endurance est augmentée grâce au battement de jambes du dauphin et en nageant sur une distance de 300 mètres.
</span></p>
