<h2 class="futura">Procédure de remboursement</h2>


<table witdh="450"><tr><td width="450">
            <h6 class="futura">Demande de Remboursement </h6>
            Envoyez à l'adresse suivant<br><br>
            
<b>3178 chemin Ste-Foy, <br>
Québec, Qc<br>
G1X1R4 <br><br></b>
            
            <ul class="bulletlist">
                <li>Une demande écrite de remboursement</li>    
                <li>Une copie de votre reçu</li>    
                <li>La feuille du crédit d'impôt fournie pour les enfants de moins de 16 ans</li>    
                <li>Une adresse de retour</li>    
            </ul><br>
            La date d’oblitération de la lettre sera prise en compte comme étant la date d’arrêt des cours.<br><br> Un frais administratif de 10% sera retenu et la différence des cours restant vous sera envoyée.

          <br>  <br><h6 class="futura">Demande de Note de crédit</h6>
 Une note de crédit peut vous être faite directement si vous téléphonez au 418-687-4045. <br><br>
 Un frais administratif de 10% sera retenu et la différence des cours restant vous sera envoyée.
 
    </td></tr></table>
